### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by 7adveo0** [jasaw/ldr-reader#1]
Hello 
Thanks for the work.

How to install it in motioneyeos?

**Comment by jasaw** [comment]
@7adveo0 The most reliable way to get this program onto your MotionEyeOS is to compile it from source, but the process is a little bit too complex for most users. You may want to try the pre-compiled binary attached below. I compiled this some time ago, so not sure whether it still works on the latest MotionEyeOS. To get the pre-compiled binary onto your MotionEyeOS, you just need to:
1. unzip it.
2. copy to your MotionEyeOS storage partition where you store all your recordings.
3. SSH to your MotionEyeOS device and enable execution permission by running `chmod +x ldr-reader`.
4. Try running the pro-compiled binary:
```
ldr-reader -h
Usage:
ldr-reader [options]

options:
 -g [gpiopin]    LDR GPIO pin number. Example: 17
 -G [gpiopin]    Light change event output GPIO pin number. High when bright.
                 Add 'i' to invert output. Can be set multiple times.
                 Example: 18 or 18i.
 -H [threshold]  High threshold in milliseconds (when dark). Default 160
 -L [threshold]  Low threshold in milliseconds (when bright). Default 30
 -D [duration]   High threshold debounce duration in seconds. Default 60
 -d [duration]   Low threshold debounce duration in seconds. Default 300
 -X [command]    Command to run when dark
 -x [command]    Command to run when bright
 -r [filepath]   Log raw values to file for debugging. Example: /var/log/ldr_raw.log
 -b              Run in the background
 -v              Increase verbose mode (can set multiple times)
 -h              Display this help page
```

**Example usage:**
If you have the light detector circuit connected to **GPIO 17** (input). When light condition changes from **dark to bright**, and you want to turn **GPIO 18 low** to turn off IR LEDs and turn **GPIO 40 high** to disable IR-cut filter on the camera. You may also want to daemonize (background) it when starting it from `userinit.sh`. This command will do just that.
`ldr-reader -g 17 -G 18i  -G 40 -b`

[ldr-reader.zip](https://github.com/jasaw/ldr-reader/files/6687579/ldr-reader.zip)

**Comment by 7adveo0** [comment]
thank you so much
